title:             GTL/KG
email:             info@gtlkg.com
description:       
author:            Katherine Van Winkle
baseurl:           ""
url:               "gtlkg.com"

# Social Profiles
instagram_username:  kittysocal


# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
