title:             GTL/KG
email:             your-email@example.com
description:       Your Company Description
author:            Katherine Van Winkle
baseurl:           ""
url:               ""

# Social Profiles
instagram_username:  kittysocal


# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
